@startuml C4 Container Diagram for FetchBolig.js
!include <C4/C4_Container>

Person(tenant, "Potential Tenant", "A person looking for housing options.")
System_Boundary(c1, "FetchBolig.js") {
    Container(web_app, "Web Application", "Alpine", "Delivers overview of housing options the user has subscribed to.")
    Container(proxy_deas, "DEAS Proxy", "Node.js, Hono", "Provides users data from DEAS's FindBolig.nu platform.")
    ContainerDb(database, "Local Storage", "Browser Storage", "Stores user's applied housing options locally.")
}
System_Ext(findBolig, "FindBolig.nu", "DEAS's housing platform. Offers waitlisting for housing options.")

Rel(tenant, findBolig, "Applies for housing options")
Rel(tenant, web_app, "Visits fetchBolig.js", "HTTPS")
Rel_R(web_app, proxy_deas, "Fetches data", "HTTPS/JSON")
Rel_R(proxy_deas, findBolig, "Retrieves data", "HTTPS/JSON")
BiRel_D(web_app, database, "Stores data", "Local Storage API")
@enduml