@startuml C4 Container Diagram for FetchBolig.js
!include <C4/C4_Component>
Container_Boundary(web_app, "Web Application") {
    Component(auth, "Authentication", "?","Takes user credentials and manages authentication with relevant proxy")
    Component(upcoming, "Upcoming agreements", "Alpine", "Displays a list of upcoming housing agreements the user has applied for.")
    Component(details, "Housing Details", "Alpine", "Shows detailed information about a specific housing option.")
    Component(messages, "Messages", "Alpine", "Show the messages related to the housing")
    Component(calendar, "Calendar Integration", "?", "Allows users to add housing agreement dates to their personal calendar.")
    Component(maps, "Map Integration", "?", "Displays housing location on a map.")
    Component(data, "Data Management", "?", "Retrives data from local storage or proxy depending on whats needed" )
}
Container(proxy_deas, "DEAS Proxy", "Node.js, Hono", "Provides users data from DEAS's FindBolig.nu platform." )
ContainerDb(database, "Local Storage", "Browser Storage", "Stores user's applied housing options locally.")

Rel(data, database, "Reads/Writes users housing data", "Local Storage API")
Rel_R(data, proxy_deas, "Provides users housing data", "HTTPS/JSON")

Rel_U(upcoming, maps, "Opens", "Maps API")
Rel_U(upcoming, calendar, "Creates Event", "iCal/ICS")
Rel_R(upcoming, details, "Navigates to", "Routing")

Rel_U(details, maps, "Opens", "Maps API")
Rel_U(details, calendar, "Creates Event", "iCal/ICS")
Rel_R(details, messages, "Navigates to", "Routing")

Rel_R(auth, data, "Exchanges user credentials", "Cookie")
Rel(upcoming, data, "Fetches", "JSON")
Rel(details, data, "Fetches", "JSON")
Rel(messages, data, "Fetches", "JSON")
@enduml